CREATE TABLE IF NOT EXISTS utente (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(50) NOT NULL,
  cognome VARCHAR(50) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  ruolo ENUM('CLIENTE','PERSONALE','PROPRIETARIO') NOT NULL DEFAULT 'CLIENTE',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
